{"path":"attachments/screenshot/Pasted image 20240928164818.png","text":"PR e R 박안 A A e ARy PR Y A 조 잔 아 7 다 M PRy 지 사 가 자 9 간 = 2o AR 시 AR 사 in _init__ Validated self = self._pydantic_validator__.validate python(data, self_instance-self) pydantic_core._pydantic_core.ValidationError: 1 validation error for User2 age Value error, 나 이는 X7 양 수 여 야 합 니 다 [type-value error, input_value=-1, input_type=int] For further information visit https://errors.pydantic.dev/2.9/v/value_error","libVersion":"0.3.2","langs":"eng+kor"}